### ISSUE TITLE
Template error in Contao 5.1

### ISSUE THREAD

**Issue by pindo-bindo** [markocupic/employee-bundle#1]
Hallo Marko,

danke für die tolle Erweiterung!

In Contao 5.1 erscheint beim Versuch ein Modul vom Typ "Mitarbeiter-Liste" oder "Mitarbeiter-Reader" folgende Fehlermeldung:

`Tried to list template options for the modern fragment type "frontend_module/employee_list" but could not find any template. In case you wanted to use the legacy type "mod_employee_list", define it explicitly in the "template" property of your controller's service tag/attribute.`

markocupic/employee-bundle 3.0.6
Contao 5.1.11
 php 8.1.22

Besten Dank für Deine Antwort!

**Comment by markocupic** [comment]
@pindo-bindo Sollte nun gefixt sein. Ist aber nicht getestet. Kannst du das bitte übernehmen? Wenn ok, bitte das Issue schliessen. Danke!

**Comment by pindo-bindo** [comment]
Hallo Marko,
super! Das Problem besteht nicht mehr.

Besten Dank!
